# This GitHub Actions workflow runs static analysis on the Python code.
# It is triggered on every push to any branch and on every pull request to the main branch.

name: Python Static Analysis

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  static-analysis:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code so the workflow can access it.
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up the Python environment.
      # Specifies the Python version to use.
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install dependencies for the workflow.
      # This includes Ruff for linting/formatting and MyPy for type checking.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy

      # Step 4: Run the Ruff linter.
      # The 'check' command analyzes the code for errors and style issues.
      - name: Run Ruff Linter
        run: |
          ruff check .
